-- Run this in your Supabase SQL editor to create tables and storage.

-- 1) Site config (single row, JSON for all editable content)
create table if not exists public.site_config (
  id int primary key default 1,
  config jsonb not null default '{}',
  updated_at timestamptz default now()
);

insert into public.site_config (id, config)
values (1, '{}')
on conflict (id) do nothing;

-- 2) Form submissions (name, email, phone)
create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  created_at timestamptz default now()
);

-- 3) RLS: public read + anon upsert so admin panel works with anon key (no auth)
alter table public.site_config enable row level security;
create policy "Public read site_config"
  on public.site_config for select using (true);
create policy "Anon upsert site_config"
  on public.site_config for all using (true) with check (true);

-- 4) RLS: anyone can insert; anon can read so admin can see submissions
alter table public.registrations enable row level security;
create policy "Anyone can insert registrations"
  on public.registrations for insert with check (true);
create policy "Anon read registrations"
  on public.registrations for select using (true);

-- 5) Storage bucket for images (logo, instructor, featured, bonuses)
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

create policy "Public read images"
  on storage.objects for select using (bucket_id = 'images');
create policy "Anon upload images"
  on storage.objects for insert with check (bucket_id = 'images');
create policy "Anon update images"
  on storage.objects for update using (bucket_id = 'images');
