-- Run this in Supabase: SQL Editor → New query → paste → Run
-- This creates only the registrations table (for the form).

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  created_at timestamptz default now()
);

alter table public.registrations enable row level security;

create policy "Anyone can insert registrations"
  on public.registrations for insert with check (true);

create policy "Anon read registrations"
  on public.registrations for select using (true);
