-- ============================================================
-- RUN THIS ONCE in Supabase Dashboard → SQL Editor → New query
-- Paste all below, click Run. You should see "Success."
-- ============================================================

-- 1) Table: site_config (for admin panel content)
create table if not exists public.site_config (
  id int primary key default 1,
  config jsonb not null default '{}',
  updated_at timestamptz default now()
);

insert into public.site_config (id, config)
values (1, '{}')
on conflict (id) do nothing;

-- 2) Table: registrations (for form submissions)
create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  created_at timestamptz default now()
);

-- 3) RLS for site_config
alter table public.site_config enable row level security;
drop policy if exists "Public read site_config" on public.site_config;
create policy "Public read site_config"
  on public.site_config for select using (true);
drop policy if exists "Anon upsert site_config" on public.site_config;
create policy "Anon upsert site_config"
  on public.site_config for all using (true) with check (true);

-- 4) RLS for registrations
alter table public.registrations enable row level security;
drop policy if exists "Anyone can insert registrations" on public.registrations;
create policy "Anyone can insert registrations"
  on public.registrations for insert with check (true);
drop policy if exists "Anon read registrations" on public.registrations;
create policy "Anon read registrations"
  on public.registrations for select using (true);

-- 5) Storage bucket (for admin image uploads)
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do nothing;

drop policy if exists "Public read images" on storage.objects;
create policy "Public read images"
  on storage.objects for select using (bucket_id = 'images');
drop policy if exists "Anon upload images" on storage.objects;
create policy "Anon upload images"
  on storage.objects for insert with check (bucket_id = 'images');
drop policy if exists "Anon update images" on storage.objects;
create policy "Anon update images"
  on storage.objects for update using (bucket_id = 'images');
